### ISSUE TITLE
Authenticate the docs using OAuth

### ISSUE THREAD

**Issue by hcphoon01** [knuckleswtf/scribe#167]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I am trying to get some docs setup to show my API routes, I've got my API routes protected by passport and I am trying to work out how I can authenticate the docs, using the OAuth Passport flow, to allow the "Try it out" feature to work

**Comment by shalvah** [comment]
That's not supported. You'd have to do it manually.

For the record, OAuth isn't supported because it's a minefield. There are so many different implementations, making it difficult to do something that works reliably. If you can think of any suggestions, please drop them.

**Comment by plokko** [comment]
You could at least implement the password OAuth flow:

Example config/scribe.php
```php
'auth' => [
        'enabled' => true,
        'in' => 'oauth:password',
        'token_url': '/oauth/token',
        'scopes' => [],
]
```

Generated securitySchemes:
```yaml
  securitySchemes:
    default:
      type: oauth2
      flows:
        password:
          tokenUrl: /oauth/token
          scopes: {}
````
I think other OAuth will be manageable but at least this is the bare minium
