### ISSUE TITLE
Accept-Header and Content-Type-Header in parameters of openapi.yaml are not allowed

### ISSUE THREAD

**Issue by LWlook** [knuckleswtf/scribe#625]
- [x] Checked the docs
- [x] Looked for open & closed tickets
- [x] Googled for the issue

**What happened?**
1. I just started an new laravel project and added fortify and scribe
2. I generated the docs + the openapi specification
3. Looked into the specification and saw following:
```
      parameters:
        - in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        - in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
```
4. Looked at the **specification for openapi** on swagger [https://swagger.io/docs/specification/describing-parameters/#header-parameters](https://swagger.io/docs/specification/describing-parameters/#header-parameters) and saw the sentence: **Note: Header parameters named Accept, Content-Type and Authorization are not allowed.**

Now my question (and probably the issue of the library): Is there a way to suppress these parameters in the openapi.yaml?

**My environment:**
 - PHP version (from `php -v`): 8.2.0
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 10.1.4
 - Scribe version (from `composer show knuckleswtf/scribe`): 4.16.0

**My Scribe config (from `php artisan scribe:config:diff`):** ------ SAME AS DEFAULT CONFIG ------

**Additional infos:**
Just to mention why this is a problem for me: I have to use swagger for displaying my documentation/api and with your library there are always two useless fields in the documentation in every request (as seen in the screenshot). And this two fields don't even do anything and are probably distracting from the real parameters.
![image](https://user-images.githubusercontent.com/39046617/221051929-9881bdb1-38ec-46eb-8401-7e63a21974ac.png)
