### ISSUE TITLE
enum support as parameters

### ISSUE THREAD

**Issue by mselmanyildirim** [knuckleswtf/scribe#626]
- [x] Version info - I'm using `scribe 4.16.0` with `laravel 10`
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
- [x] I've searched the word `enum` in the documentation, but only found one occurence which was irrelevant.

The question is rather related to the generated `openapi.yaml` file.   
As shown in the [documentation](https://swagger.io/docs/specification/adding-examples/) page, openapi specification supports `enum`s as parameters. 
```
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
      example: approved 
```   
This helps the documentation to show dropdown menus for parameters having several predefined values, as in the following image:   

![image](https://user-images.githubusercontent.com/61732943/221942940-97916f4d-ca3e-4a9d-8f31-dba72cda97b6.png)
  
**Question**
So, do we have a way to annotate a parameter in the comment blocks so that scribe generates the `openapi.yaml` file with `enum`  value list? I guess I can override this via `nn.yaml` or `config/scribe.php` files, but it would be nice to do this via comment blocks.  
Thanks!
